{{- if .Values.kubescapeStorage.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubescapeStorage.authDelegatorClusterRoleBindingName" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "kubescapeStorage.serviceAccountName" . | quote }}
  namespace: {{ .Values.ksNamespace | quote }}
{{- end }}
