{{- if and .Values.kubevuln.enabled .Values.kubescape.submit .Values.kubescapeStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "kubescape-aa-storage-etcd"
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: "kubescape-aa-storage-etcd"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.backingStorage }}
  {{- if ne .Values.persistence.storageClass "-" }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
