{{- if .Values.kubescapeStorage.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubescapeStorage.authReaderRoleBindingName" . | quote }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # This is a default role name provided by K8s and should not be templated or changed
  name: "extension-apiserver-authentication-reader"
subjects:
- kind: ServiceAccount
  name: {{ include "kubescapeStorage.serviceAccountName" . | quote }}
  namespace: {{ .Values.ksNamespace | quote }}
{{- end }}
