{{- if .Values.kubescapeStorage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubescapeStorage.backingStorage.service.name" . | quote }}
  namespace: {{ .Values.ksNamespace | quote }}
  labels:
    {{ .Values.kubescapeStorage.backingStorage.deployment.labels | toYaml | nindent 4 }}
spec:
  type: "ClusterIP"
  selector:
    {{ .Values.kubescapeStorage.backingStorage.deployment.labels | toYaml | nindent 4 }}
  ports:
    {{- include "kubescapeStorage.backingStorage.service.port" . | nindent 4 }}
{{- end }}
