{{- if .Values.kubescapeStorage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubescapeStorage.apiServer.deploymentName" . | quote }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{ .Values.kubescapeStorage.k8sApiserver.deployment.labels | toYaml  | nindent 4}}
spec:
  replicas: {{ .Values.kubescapeStorage.k8sApiserver.deployment.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.kubescapeStorage.k8sApiserver.deployment.labels | toYaml | nindent 6}}
  template:
    metadata:
      labels:
        {{ .Values.kubescapeStorage.k8sApiserver.deployment.labels | toYaml | nindent 8}}
    spec:
      serviceAccountName: {{ include "kubescapeStorage.serviceAccountName" . | quote }}
      containers:
      - name: apiserver
        image: {{ printf "%s:%s" .Values.kubescapeStorage.k8sApiserver.deployment.image.repository .Values.kubescapeStorage.k8sApiserver.deployment.image.tag  | quote }}
        imagePullPolicy: {{ .Values.kubescapeStorage.k8sApiserver.deployment.image.pullPolicy | quote }}
        args: [ "--etcd-servers=http://{{ include "kubescapeStorage.backingStorage.service.name" . }}:{{ include "kubescapeStorage.backingStorage.containerPort" . }}" ]
{{- end }}
