{{- if .Values.kubescapeStorage.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "kubescapeStorage.serviceAccountName" . | quote }}
  namespace: {{ .Values.ksNamespace | quote }}
{{- end }}
