{{- if and .Values.nodeAgent.enabled .Values.kubescapeStorage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nodeAgent.config.name }}
  namespace: {{ .Values.ksNamespace }}
data:
  ConfigurationFile.json: |
    {
        "sniffer": {
            "services": [
                {
                    "Name": "relevantCVEs"
                }
            ],
            "maxSniffingTimePerContainer": {{ .Values.nodeAgent.config.maxSniffingTime }}
        },
        "falcoEbpfEngine": {
            "kernelObjPath": "/root/.falco/falco-bpf.o",
            "ebpfEngineLoaderPath": "/etc/node-agent/resources/ebpf/falco/userspace_app"
        },
        "node": {
            "name": ""
        },
        "db": {
            "updateDataPeriod": {{ .Values.nodeAgent.config.updateDataPeriod }}
        },
        "clusterName": "{{ regexReplaceAll "\\W+" .Values.clusterName "-" }}",
        "accountID": "{{ .Values.account }}"
    }
{{- end}}