kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.operatorServiceAccountName }}-roles
  namespace: {{ .Values.ksNamespace }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["spdx.softwarecomposition.kubescape.io"]
  resources: ["sbomspdxv2p3s", "vulnerabilitymanifests", "sbomspdxv2p3filtereds"]
  verbs: ["create", "get", "update", "delete", "watch", "list", "patch"]
